### ISSUE TITLE
Setup Avalon Test Instance and Conduct Terraform Apply in Unrestricted AWS Environment

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#1]
**Monday 8/31**
- [x] Get Avalon running in unrestricted AWS account (running in a different region)
- [x] Confirm Middleware has reviewed the Avalon wiki system requirements
- [x] Confirm AWS environment has been requested and setup and the team has access 
- [x] Solomon demo the steps taken to setup https://test.emoryavalon.com/
- [x] Communicate any risks, issues or dependencies for Terraform Apply in AWS restricted environments

**Tuesday 9/1**
- [x] Confirm that CB, DM, WU, BW, AZ, DG, AH, AC has access to AWS for Terraform Apply or other work
- [x]  Confirm everyone has read and understand following https://github.com/avalonmediasystem/avalon-terraform

**Comment by libdgg** [comment]
SH: See if we can get Avalon running in unrestricted AWS account (running in a different region). Helps test terraform - explore and see how to setup in a restricted account.

SH: Request a user (multiple users if we plan on test prod). We request and Paul P creates the user. Document the process. Each user will have a key, we may need a place to store (e.g. vault).

DG: Loop in Core Sys (zoom call, install TKI client, AWS CLI client)

CB: COMPLETE add SH and MP to the LTDS Avalon Course Reserves (aka 247) AWS account.

For the restricted, test .tf files on individual spaces. The output of this work results in the different environments.
In DLP we have arch, test and prod. - For Avalon we can plan for 3 environments/3 users, start with 2 (test and prod)

**Comment by libdgg** [comment]
No blockers, Solomon has not initiated anything with this environment yet.

**Comment by lovinscari** [comment]
Update from Solomon on work completed 8/26/20 - "I am still experimenting with the Terraform config. I feel like I've ironed out most issues besides the docker problem, which I've submitted an issue with the repo maintainer here: https://github.com/avalonmediasystem/avalon-terraform/issues/19 (edited) 
12:47
He responded quickly to a minor issue I submitted Tues, so hopefully I will get a response soon. "

**Comment by SolomonHD** [comment]
I have created AWS accounts in the LTDS Standard account for: wulman dgoans libah cbrittl dmatlaw bwatso9 acoope5 azotov

I sent them their initial passwords via Slack DM.
