### ISSUE TITLE
Prepare and submit request for Shibboleth identity management requirements

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#10]

**Comment by libdgg** [comment]
What are metadata elements? Service owner to sign off on the request.

**Comment by lovinscari** [comment]
Started completing forms

**Comment by lovinscari** [comment]
Update from Alex on work completed 8/26/20 - "Add requirements for shib request to ticket EOB today or tomorrow?"

**Comment by libah** [comment]
**Shibboleth Login Application Requirements**

There are two forms that are required, the requirements form and confidentiality form. The forms cannot be submitted without all of the information, which we currently don't have, like the official name, URL, and links to all instances. The links to the forms and the KB article are below. 

**Requirements for requesting a shibboleth login:**

Application Name, Purpose & URL:
Application Administrator Name:
Supervisor Name:
List names (and NetIDs if applicable) of all the application administrators:

**Metadata:**
entityID:
Test URL:
Internally or externally hosted?

**Other required information**
How are the servers protected from unauthorized access and from attack (physically and via network)?
Does the application store identifiable student data?
Does the application store identifiable personal healthcare information?

Requestor’s Signature:

Supervisor’s Signature

Link to Knowledge Base Article and Forms

https://emory.service-now.com/sp?id=kb_article&sys_id=409ea0281b0eb704a8441f4ead4bcb9a&table=kb_knowledge

**Comment by lovinscari** [comment]
The URL has been confirmed as https://avreserves.libraries.emory.edu

**Comment by lovinscari** [comment]
Should be able to move to submit this today or tomorrow once Ann meets with Alex.

**Comment by libah** [comment]
**Still need this information:**


- Submitter's/Requestor's Name:
- Application Administrator Name:
- List names (and NetIDs if applicable) of all the application administrators:
- Test URL:
- How are the servers protected from unauthorized access and from attack (physically and via network)?

**Comment by lovinscari** [comment]
Alex and Doug to discuss during their check in meeting today to get details needed (comment from 9/10).

**Comment by libdgg** [comment]
- DLP Shibboleth form for reference: https://emory.app.box.com/file/644702174218
- Complete form so it is ready to submit.
- Entity ID is https://avreserves.libraries.emory.edu
- Test URLs: arch, test, prod (we can change that later)
- CB confirming time for Ruby/SAML to be integrated into Avalon Repo - we can't give Gerry any metadata until then. Could submit the form during that same sprint. Coordinate with CB on this.

**Comment by libdgg** [comment]
@rotated8 are you able to confirm the time for Ruby/SAML to be integrated into Avalon Repo? We can't give Gerry any metadata until then. We are thinking we could submit the form during that same sprint that you are working on that integration. Thoughts?

**Comment by libah** [comment]
The form is filled out with all the information we have available at this time. It can be viewed here:
https://emory.app.box.com/folder/122468943197

**Comment by libdgg** [comment]
Moving to blocked until we find out about any requirements or blockers from Anne Marie regarding Ruby/SAML.

**Comment by lovinscari** [comment]
Collin reached out to Gary on the Identity Mgmt team which was updated on the "Setup Shibboleth Ticket"

**Comment by libdgg** [comment]
Q:  Can Ann proceed with submitting  this request? 
A: Yes

**Comment by libdgg** [comment]
Ann posted documents on  slack and we are planning next steps for signatures.

**Comment by lovinscari** [comment]
Collin and Doug to sign the documents.

**Comment by AGCooper** [comment]
Submitted the SN request INC03486987
