### ISSUE TITLE
LDS Group Request

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/avalon#101]
From Anne Marie: "Well it looks like we can make it easier for you!  If you want to open a ticket to IdM to create a role for Avalon Admins, just tell us who should own it and who should be allowed to add and subtract people and we can work with Messaging to set up the the LDS group.  And we can teach people how to add members to a role (which will automatically add them to the LDS group).  We might need more info but I am sure we will ask when we get the ticket.  Anytime you are ready, we can help!"

- [x] Group Owner?

- [x] Who should be allowed to add and subtract people?

**Comment by libdgg** [comment]
This ticket is related to other shib tickes. We were keeping it active while we worked on the other shib tickets.

**Comment by AGCooper** [comment]
Still waiting on Shib integration working.
