### ISSUE TITLE
Creating Users Via Console

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#104]
Need PPID

- [x] Solomon user created

- [x] Alex user created

**Comment by lovinscari** [comment]
Adding @AGCooper to test after shib is completed.

**Comment by devanshu-m** [comment]
Alex tested his login which was successful.

We need to work on better error handling at some point after user groups ticket is done.

**Comment by lovinscari** [comment]
@devanshu-m - since Alex confirmed his login was successful, can we close this issue?

**Comment by devanshu-m** [comment]
yes, closing. @lovinscari
