### ISSUE TITLE
Move Arch and Test to F5

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#109]

**Comment by SolomonHD** [comment]
Arch and Test have been moved to the F5. They are all on one VIP in the ag_web partition. This did require that I setup multiple pools and create two custom iRules for routing, they're called avalon_443_routing and avalon_80_routing.

Acceptance criteria is that it should be reachable for people who don't have aws@emory VPN core access. I believe that's @lovinscari ?
