### ISSUE TITLE
Notify Canvas team of project start and timeline/availability for LTI integration work

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#11]

**Comment by libdgg** [comment]
I contacted Lee to let him know. I am waiting on a response before closing this ticket.

**Comment by lovinscari** [comment]
Someone from the Canvas team responded with questions regarding the request. Doug to respond to their questions - some of this might be around the need to get the security review started.

**Comment by libdgg** [comment]
Haynes Chewning responded. I'm proposing we close this ticket since next steps for implementation are indicated with their response. I'll add notes to the other LTI tickets.
