### ISSUE TITLE
Upgrade to Avalon 7.2

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/avalon#122]
We need to rebase our customizations onto 7.2 so we can take advantage of the LTI configuration work Phuong did upstream.

- [x] Remove LTI customizations
- [x] Rebase master (7.2) into main
- [x] Resolve conflicts

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/avalon/pull/124

**Comment by devanshu-m** [comment]
Acceptance for this ticket:

- [ ] be able to login
- [ ] upload a new vide
- [ ] stream the uploaded video

**Comment by lovinscari** [comment]
Associate one of the videos in prod with a course in Canvas and then confirming course can stream and is accessible via Canvas. @bwatson78 has agreed to test this as well as edit the video.

**Comment by bwatson78** [comment]
Test complete:

https://emory-my.sharepoint.com/:v:/g/personal/bwatso9_emory_edu/EYHISO9m-TxNkVLfGBGS9aQBihJeNELsSy5NkCk6uYwWKQ?e=wnRJab
