### ISSUE TITLE
Streaming Not Working

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/avalon#125]
Streaming is not working since the rebuild of the ec2 performed the morning of the 11/30.
Most likely an issue with the docker config and the new s3-helper container.

**Comment by libdgg** [comment]
SH update - Issue identified in docker compose - environment variable "slash" change needed.
Applied change to all 3 environments.

**Comment by libdgg** [comment]
At least 2 people below need to confirm streaming is working in prod. If so we can close this ticket.

Please upload a video and stream.

- [ ] Devanshu
- [ ] Brad
- [ ] Alex
- [ ] Collin
- [ ] Zo
- [ ] Solomon
