### ISSUE TITLE
Commit Emory Docker Compose to AWS Min

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#126]
SH Open 2 PRs and have Phuong review/accept.

- [x] Fedora
- [x] Streaming Change

**Comment by SolomonHD** [comment]
I have messaged Phuong about the changes needed to incorporate the emory branch into aws_min.

**Comment by libdgg** [comment]
We have a different config on our fedora for SSL. We had to change a few things. For docker we had to create a branch. 
Risk is that we would miss updates so we should merge into aws_min (Phuong's baseline).
Phuong has to change his aws_min branch to match our branch for fedora SSL options.

The streaming change is related to our private bucket. Phuong's default is a public bucket.

SH will re-familiarize what the changes are and then open the PRs in avalon_terraform and avalon_docker

**Comment by SolomonHD** [comment]
Phuong worked with me on this today and it's done.
The PRs that were merged are: [1](https://github.com/avalonmediasystem/avalon-terraform/pull/28),[2](https://github.com/avalonmediasystem/avalon-docker/pull/50),[3](https://github.com/avalonmediasystem/avalon-docker/pull/49),[4](https://github.com/emory-libraries/avalon-terraform/pull/23)

With these changes the emory branch of avalon-docker has been deleted and we are back to building from the aws_min branch of avalon-docker.

**Comment by rotated8** [comment]
Awesome!
