### ISSUE TITLE
Create Avalon Admins for Production to Prep for Operational Status

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#128]
For the Avalon prod, arch, and test sites, please add the following people with permissions to be able to add videos and manage content. Please advise if there are questions or concerns with this request.

- [x] James Steffen, NETID: jsteffe, EMAIL: jsteffe@emory.edu
- [x] Nina Rao, NETID: nraogra, EMAIL: nina.rao@emory.edu
- [x] Doug Goans, NETID: dgoans, EMAIL: dgoans@emory.edu
- [x] Cari Lovins, NETID: clovins, EMAIL: cari.lovins@emory.edu

**Comment by AGCooper** [comment]
James S. was already added (he should also be able to add people).

Nina, Doug, Cari have been added.

@libdgg and @lovinscari could you test and see if you get the manage tab please?

![image.png](https://images.zenhubusercontent.com/5c75948e37910a45fad7cb77/f4a37e2b-9483-4173-baba-4c20fa182520)

**Comment by libdgg** [comment]
I can log in and see the Manage Tab here
https://avreserves-test.libraries.emory.edu/

When I go to 
https://avreserves.libraries.emory.edu
https://avreserves-arch.libraries.emory.edu/

I get the following error:
"The change you wanted was rejected. Maybe you tried to change something you didn't have access to. If you are the application owner check the logs for more information."

**Comment by AGCooper** [comment]
@libdgg That may need @devanshu-m to look at it.

**Comment by devanshu-m** [comment]
@libdgg @AGCooper the new code to make logins for duplicate users possible from both canvas and shib was only on test. That code has now been pushed to prod and arch.

**Comment by libdgg** [comment]
@libdgg and @lovinscari please test (also test with James S.)

**Comment by libdgg** [comment]
Met with James on 12/10. Changing the date on this ticket to next week to give us time to confirm login works for Nina and Cari.

**Comment by libdgg** [comment]
All users were setup the same way and 2 out of 4 are successful. Close this ticket. Any issues can be resolved via a request or a new ticket.
