### ISSUE TITLE
Create account for Rosalyn Metz in Canvas 

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/avalon#129]
She should be set as a test student in order to see what other students are seeing with Avalon from Canvas. Doug will reach out to Haynes to get this completed.

**Comment by libdgg** [comment]
Haynes has added Rosalyn as a Student in the test course.
https://canvas.emory.edu/courses/87211/users

He emailed her to let her know on 12/8/2020 at 12:22pm.

**Comment by libdgg** [comment]
we have confirmed that she is in the course and has accepted the invite.
