### ISSUE TITLE
Implement and manage the assistance agreement with Indiana University

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#13]
- [x] Agreement start date

- [x] ZenHub tickets are in place that correspond to the assistance request (see Epic)

- [x] Phuong access to ZenHub or other systems

- [x] Assign tasks and determine meetings/schedule with Phuong to account for time/billing

**Comment by lovinscari** [comment]
Update from Doug on 8/27/20 - Work has started on this. Moving to In Progress

**Comment by lovinscari** [comment]
Need to modify this ticket for tracking if the SOW is approved as a measure to track hours and spending on SOW.

**Comment by libdgg** [comment]
I'll be checking in with Phuong weekly for updates to the timesheet.
