### ISSUE TITLE
Remove search box from header

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/avalon#132]
On narrow screens the search box takes up an odd space, and we don't really want to encourage users to search the site.

![avalon-header.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/25591d98-9fd8-47a9-9465-44902dc6eb04)

This is done when
- [ ] A user can browse the site, and no search box is present in the header.

**Comment by devanshu-m** [comment]
There are search boxes elsewhere as well. Are we looking to remove all of them or only from the header? @rotated8

**Comment by rotated8** [comment]
Only the header.

**Comment by libdgg** [comment]
CB approves

**Comment by devanshu-m** [comment]
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/bbb0dc2c-1cde-495f-b83f-c8470543ffb0)

Search box is gone from header as expected. Closing.
