### ISSUE TITLE
Change text shown for logged in users

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/avalon#133]
The long "username" is not helpful to users, so change the wording to "You are signed in"

![avalon-header.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/a85d37e1-fa67-4ad6-8947-a320c9799959)

This is done when a logged in user sees the above text instead of the hash.

**Comment by libdgg** [comment]
CB approves

**Comment by devanshu-m** [comment]
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/22a656f3-0c57-4ea3-9240-3be1e86a5289)

Search box is gone from header as expected. Closing.
