### ISSUE TITLE
Complete Project Charter

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#14]

**Comment by libdgg** [comment]
Blocked: spending time doing work on project tickets related to infrastructure setup. Hope to get back to this before end of Friday.

**Comment by lovinscari** [comment]
Draft completed by DG and CL to review on 9/8/20. Should be able to get this closed by end of week.

**Comment by libdgg** [comment]
DG, CL met with James Steffen. Incorporated changes into the charter. We need to do a final review before we can close this ticket.

**Comment by libdgg** [comment]
Box tasks for the Service Team and Technology team were created to approve the charter by 5pm Monday 9/28/2020.
