### ISSUE TITLE
Streaming Issue After Pausing Video

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#141]
Steps to replicate the issue:

1. Start Video
2. Pause after a minute
3. Keep browser open with the video on pause for about 30 minutes (a 10 minute pause seems to be ok but longer than that seems to be an issue).
4. Resume playing and it will start playing for about 1 minute and then throw the following error and then stop.

![Screen Shot 2020-12-18 at 7.43.49 PM.png](https://images.zenhubusercontent.com/5c0ec309cd03b2349870e625/74f7b42b-f2c7-4b4e-a807-1aa925aa2ede)

**Comment by phuongdh** [comment]
FYI this is a [configurable setting](https://github.com/avalonmediasystem/avalon-docker/issues/51#issuecomment-748277570)  
Also checkout [this wiki page](https://wiki.dlib.indiana.edu/display/VarVideo/Configuration+Files) if you haven't come across it.

**Comment by libdgg** [comment]
Timeout set for 2 hours.
SH pushed up a branch in the test instance.
SH create a PR
MP review the PR
DM creates the new release and move this ticket through test, accept.
DG accept
Soft Eng will move to prod and close

**Comment by libdgg** [comment]
@SolomonHD @rotated8 any progress on this ticket?

**Comment by SolomonHD** [comment]
@libdgg the change I pushed up to https://avreserves-test.libraries.emory.edu/ seems to have fixed the issue. I've tested it by pausing a stream for an hour, then resuming with no issues. Please test it yourself.

**Comment by rotated8** [comment]
@SolomonHD Please put in a PR for this change.

**Comment by libdgg** [comment]
Here is the PR
https://github.com/emory-libraries/avalon/pull/145

Confirm next steps:
MP review the PR
DM creates the new release and move this ticket through test, accept.
DG accept
Soft Eng will move to prod and close

**Comment by SolomonHD** [comment]
https://github.com/emory-libraries/avalon/pull/145

**Comment by libdgg** [comment]
@devanshu-m and @rotated8 Mark P approved the PR. Please confirm the next steps below are still accurate:

DM creates the new release and move this ticket through test, accept.
DG accept
Soft Eng will move to prod and close

**Comment by libdgg** [comment]
I tested it with a pause for 30 minutes and 90 minutes and 2.5 hours and it is working as expected for me.
