### ISSUE TITLE
Setup Project Communication and Document Channels

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#15]
- [x] Slack: #avalon
- [x] Box: https://emory.app.box.com/folder/119803258734
- [x] Google Project Space: https://drive.google.com/drive/u/0/folders/1WOntVl2fIuAVtlZtiAgr6K-SMXRSpNyX
- [x] GitHub: https://github.com/emory-libraries/avalon
- [x] ZenHub: https://app.zenhub.com/workspaces/video-course-reserves-5f40265a5131320016940571/board?repos=289353095
- [x] Listserv (do we need this?)

Descoping the wiki as there needs to be work to upate permissions, users and structure for the space.
- [x] Wiki Space: https://wiki.service.emory.edu/pages/viewpage.action?pageId=172512552
- [x] [Use Box for now to deposit technical documentation](https://emory.app.box.com/folder/122884913335)

**Comment by lovinscari** [comment]
@libdgg - If we can decide on specifics for listserv then I am happy to set this up. 

I need the following information:

Name of Listserv
Purpose 
Members

**Comment by lovinscari** [comment]
Cari to add to checkin with James Steffan

**Comment by libdgg** [comment]
Blocked until we meet with James Steffen to see if/how this listserv would relate to the service (that will inform the purpose).

**Comment by libdgg** [comment]
2 Blockers
- Confirm details to setup listserv
- address wiki permissions issues and LTDS space for product documents

**Comment by lovinscari** [comment]
Permissions in Wiki need to be addressed and feedback from James S. needed for listserv.

**Comment by libdgg** [comment]
Descoped the wiki as it will take more time and resources to configure it for new product documentation. Use box to deposit technical documentation for the time being. We just need to complete the listserv work to close this ticket.
Box space for technical documentation
https://emory.app.box.com/folder/122884913335
