### ISSUE TITLE
Confirm resourcing requirements, scope, and responsibilities of Service Team with Lisa Macklin (James)

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#21]

**Comment by lovinscari** [comment]
Risk if not completed by 9/11/20 - Could delay the scheduled activities for the service team including preparing content, preparing for testing, etc. 

DG and CL scheduled to meet with James Steffan on 9/10/20.

**Comment by libdgg** [comment]
We are finalizing the team membership with James Steffen. The final version is in the project charter but here is the current info for the Service Team.

- James Steffen (Research and Engagement / Workflow Development Team / Service Manager)
- Jessica Perlove, David Smith, Kyle Fenton, Nina Rao, Colin Bragg (Access Services / Workflow Development Team / Digitization Team / Course Reserves)
- Melanie Kowalski (Scholarly Communications / Workflow Development Team)
