### ISSUE TITLE
Review Architecture/Security Review process and begin plannning

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/avalon#23]
- Wiki site for ART review team process: https://wiki.service.emory.edu/display/cita/Architecture+Review+Team
- Meetings are held every Thursday at the North Decatur Building, 3rd floor in the Sweetwater conference room 305D, and also online using Zoom. The meeting time is from 1-2pET. 

- The ART lead will forward the online meeting information to the project lead once a review date is set. The project lead is expected to inform all project team members of the meeting date, venue and time.
- It is recommended to submit for a security review AFTER the ART review if determined by ART that one is required.

**Comment by libdgg** [comment]
Architecture Review preparation:
- Confirm the hosting environment
- Draft the architecture diagram
- In preparation for drafting the ART review checklist we need to confirm which template is needed: Custom / Developed (In-house, Including AWS) Application Checklist or Hosted / Cloud Application Checklist (you will need to export a copy to a Word document so the team technical team can fill in the information)
- Architecture Review Team Wiki page

Security Review Preparation:
Security review intake questions  (more than likely we will go through the security process so I put together the questions we will need to answer)
- These answers will need to be placed in a ServiceNow request form once all parties have had a chance to review them.

You’ll find the documents which describe the LITS processes for the Security and ART reviews in Box in their individual folders: https://emory.app.box.com/folder/121231153604

Emory Login Request – Shibboleth

**Comment by lovinscari** [comment]
DG is going to start preparing the documentation on 9/8/20. Believes he can complete the work and submit request by 9/11/20

Risk if not completed by 9/11/20 - Could delay the review and approval by LITS and ATS requires security review to be completed before LTI integration.

**Comment by libdgg** [comment]
Draft AWS diagram https://app.lucidchart.com/documents/view/1b5e09ad-0b58-4959-af93-2d0a3d5dc774/qFusNXo_0pQU

**Comment by libdgg** [comment]
Architecture Review preparation:

- [ ] Confirm the hosting environment = AWS@Emory
- [ ] Draft the architecture diagram

Confirm which template is needed:
- [ ] NEEDED Custom / Developed (In-house, Including AWS) Application Checklist
- [ ] NOT NEEDED Hosted / Cloud Application Checklist (you will need to export a copy to a Word document so the team technical team can fill in the information)

Next Steps

- [ ] [Draft ART review document is ready](https://wiki.service.emory.edu/pages/viewpage.action?pageId=172514610) for the group to review and complete (includes diagram).
- [ ] Schedule review and attendees
- [ ] Conduct and complete review
- [ ] Determine if a security review is needed as a next step

**Comment by lovinscari** [comment]
Publish the Lucidchart and put a link to the published version in Box for comment and review. DG and CL to complete this task during 1-2-1 meeting today.

**Comment by libdgg** [comment]
https://emory.app.box.com/file/717654530906

**Comment by libdgg** [comment]
Team met and completed most of the ART review document. The network document needs review/edits. Working session scheduled for 9/23 at 1pm.

**Comment by libdgg** [comment]
Documents submitted. Closing this ticket as the next step is the security review on Oct 1st. There is a separate ticket to track the actual review..
