### ISSUE TITLE
Shibboleth Integration

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#25]
- [x] install ruby-saml gem
- [x] compare setup in https://github.service.emory.edu/LITS/salesforce-urc/ to setup in curate
- [x] copy relevant parts of above into this app

**Comment by libdgg** [comment]
Multiple paths:

- Ruby/SAML Gem is **recommended**, it will not require us to fork avalon-docker
- Shibboleth Gem, would require a shib binary and forking.

See: https://hub.docker.com/r/unicon/shibboleth-sp

**Comment by libdgg** [comment]
CB will reach out to Anne Marie as next step.

**Comment by libdgg** [comment]
Solomon provided this info in slack.
Here is an example of the omniauth-saml (works more or less like ruby-saml) gem being used:
https://github.service.emory.edu/LITS/salesforce-urc

**Comment by rotated8** [comment]
I reached out to Gerry today. I'll comment again when I get a response.

**Comment by rotated8** [comment]
According to Gerry, there is no technical reason a SAML SP would not work with any available attributes.

**Comment by lovinscari** [comment]
Needs the enterprise GitHub to open up. CB will create a separate ticket to review the enterprise GitHub.

**Comment by SolomonHD** [comment]
Here's a short code snippet that reflects the environment variables that will be on the server
```ruby
  # OmniAuth configuration settings
  config.idp_slo_target_url = ENV['IDP_SLO_TARGET_URL']
  config.assertion_consumer_service_url = ENV['ASSERTION_CS_URL']
  config.assertion_consumer_logout_service_url = ENV['ASSERTION_LOGOUT_URL']
  config.issuer = ENV['ISSUER']
  config.idp_sso_target_url = ENV['IDP_SSO_TARGET_URL']
  config.idp_cert = ENV['IDP_CERT']
  config.certificate = ENV['SP_CERT']
  config.private_key = ENV['SP_KEY']
  config.attribute_statements = {}
  config.uid_attribute = "urn:oid:0.9.2342.19200300.100.1.1"
  config.security = {
     :want_assertions_encrypted  => true, #makes a 2nd KeyDescriptor, this one says use="encryption"
     :want_assertions_signed  => true, # goes on md SPSSODescriptor tag
  }
end
```
This should go in an initializer. The uid_attribute urn may need to be changed, I'm not sure if that's serialNumber or netid
All the shibboleth environment variables are populated on the server as of 10/16 builds.
The current setup is for all the environments to use "https://avreserves.libraries.emory.edu" as the entityID. Ask Gerry to add the other avreserves as endpoints.
After omniauth saml is integrated into the app, the metadata will be found at /auth/saml/metadata. It's usually best to right click to "view source" copy the xml, then run it through an xml formatter website.

**Comment by rotated8** [comment]
SE now has access to the repo, can start looking at the implementation https://github.service.emory.edu/LITS/salesforce-urc/blob/develop/app/controllers/omniauth_callbacks_controller.rb

**Comment by SolomonHD** [comment]
Shibboleth is working on all environments, I can pull metadata from each one. We're ready for the IDP to add our configuration.

**Comment by libdgg** [comment]
@AGCooper please confirm that you will take any next steps with the Shib paperwork and that IDP has has added our configuration. If so we can close this ticket and can create another ticket for the admin role to assign users for who is or is not an admin.

**Comment by bwatson78** [comment]
Our blocker for getting it to work ended up being that the test users that were created for canvas had no user metadata attached, including email, which is a required field for `user`:
```
omniauth.auth: #<OmniAuth::AuthHash credentials=#<OmniAuth::AuthHash secret="prHP5Cq9Nvq48xOsGMRS4bGeN4TBYiR0" token="avalon-prod"> extra=#<OmniAuth::AuthHash consumer=#<OmniAuth::AuthHash> context_id="b947a408302af0c107521f40094046e5d9ff6a2b" context_name="FA20_AVA_PROD_101" raw_info=#<OmniAuth::AuthHash context_id="b947a408302af0c107521f40094046e5d9ff6a2b" context_label="FA20_AVA_PROD_101" context_title="Avalon Prod Course" custom_canvas_enrollment_state="active" ext_roles="urn:lti:instrole:ims/lis/Student,urn:lti:role:ims/lis/Learner,urn:lti:sysrole:ims/lis/User" launch_presentation_document_target="iframe" launch_presentation_locale="en" launch_presentation_return_url="https://canvas.emory.edu/courses/87211/external_content/success/external_tool_redirect" lti_message_type="basic-lti-launch-request" lti_version="LTI-1p0" oauth_callback="about:blank" oauth_consumer_key="avalon-prod" oauth_nonce="er4YFx3pJYLjvLRUYkj3AT2xVArSFfqJqBxx4nRs2A" oauth_signature="ileXSXwzATr1nSYYUSZkeKrelmg=" oauth_signature_method="HMAC-SHA1" oauth_timestamp="1605899473" oauth_version="1.0" resource_link_id="1d83b7b7857022908f728a8c853ef74926642e74" resource_link_title="Avalon Prod iFrame" roles="learner" tool_consumer_info_product_family_code="canvas" tool_consumer_info_version="cloud" tool_consumer_instance_contact_email="notifications@instructure.com" tool_consumer_instance_guid="Cv9zljwSCHryURcGdiNqvcWy9BR4Byb0Y8kA4Yq4:canvas-lms" tool_consumer_instance_name="Emory University" user_id="cd1d338bd3431adf6825a238579d7806d45caa7c">> info=#<OmniAuth::AuthHash::InfoHash email=nil first_name=nil image=nil last_name=nil name="cd1d338bd3431adf6825a238579d7806d45caa7c"> provider="lti" uid="cd1d338bd3431adf6825a238579d7806d45caa7c">
I, [2020-11-20T19:11:13.771010 #21] INFO -- : omniauth.auth: #<OmniAuth::AuthHash credentials=#<OmniAuth::AuthHash secret="prHP5Cq9Nvq48xOsGMRS4bGeN4TBYiR0" token="avalon-prod"> extra=#<OmniAuth::AuthHash consumer=#<OmniAuth::AuthHash> context_id="b947a408302af0c107521f40094046e5d9ff6a2b" context_name="FA20_AVA_PROD_101" raw_info=#<OmniAuth::AuthHash context_id="b947a408302af0c107521f40094046e5d9ff6a2b" context_label="FA20_AVA_PROD_101" context_title="Avalon Prod Course" custom_canvas_enrollment_state="active" ext_roles="urn:lti:instrole:ims/lis/Student,urn:lti:role:ims/lis/Learner,urn:lti:sysrole:ims/lis/User" launch_presentation_document_target="iframe" launch_presentation_locale="en" launch_presentation_return_url="https://canvas.emory.edu/courses/87211/external_content/success/external_tool_redirect" lti_message_type="basic-lti-launch-request" lti_version="LTI-1p0" oauth_callback="about:blank" oauth_consumer_key="avalon-prod" oauth_nonce="er4YFx3pJYLjvLRUYkj3AT2xVArSFfqJqBxx4nRs2A" oauth_signature="ileXSXwzATr1nSYYUSZkeKrelmg=" oauth_signature_method="HMAC-SHA1" oauth_timestamp="1605899473" oauth_version="1.0" resource_link_id="1d83b7b7857022908f728a8c853ef74926642e74" resource_link_title="Avalon Prod iFrame" roles="learner" tool_consumer_info_product_family_code="canvas" tool_consumer_info_version="cloud" tool_consumer_instance_contact_email="notifications@instructure.com" tool_consumer_instance_guid="Cv9zljwSCHryURcGdiNqvcWy9BR4Byb0Y8kA4Yq4:canvas-lms" tool_consumer_instance_name="Emory University" user_id="cd1d338bd3431adf6825a238579d7806d45caa7c">> info=#<OmniAuth::AuthHash::InfoHash email=nil first_name=nil image=nil last_name=nil name="cd1d338bd3431adf6825a238579d7806d45caa7c"> provider="lti" uid="cd1d338bd3431adf6825a238579d7806d45caa7c">
```
That was blocking our users from persisting, and before finding this, we'd get the flash message that we successfully signed in, but the "Sign In" button was still there.

New PR fixes this by protecting against nil email: https://github.com/emory-libraries/avalon/pull/118

**Comment by devanshu-m** [comment]
The uid here in the lti response looks unusual and incorrect. @SolomonHD
