### ISSUE TITLE
Submit Request for AWS Machine Users (for Restricted AWS)

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#29]
- [x] Request a user (arch, test and prod). We request and Paul P creates the user. 
- [x] Document the process. 
- [x] Each user will have a key, we may need a place to store (e.g. vault). 
- [x] Doublecheck permissions, and what to call the buckets. Submit request to Paul by Friday.

**Comment by libdgg** [comment]
NOTE: Today (8/25) I emailed Paul P. to inform him of our Avalon plans and the need to move requests through quickly.

**Comment by lovinscari** [comment]
SH - Needs to know the bucket names before moving forward on this ticket. Terraform creates the buckets. 

Risk if not completed by 9/11/20 - Not having the buckets ready for the internal environment. SH determines this risk as low. The process takes about a week. DG could communicate with Paul Peterson the need to have this turned around quickly.

**Comment by SolomonHD** [comment]
I have submitted 3 service account requests:

- arch: [INC03459873](https://emory.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D7c304bb81b1b54d0c725964c0a4bcbd2%26sysparm_record_target%3Dincident%26sysparm_record_row%3D1%26sysparm_record_rows%3D1%26sysparm_record_list%3Dnumber%3DINC03459873%5EORDERBYnumber)
- test: [INC03459878](https://emory.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3Da4b00ff81b1b54d0c725964c0a4bcb30%26sysparm_record_target%3Dincident%26sysparm_record_row%3D1%26sysparm_record_rows%3D1%26sysparm_record_list%3Dnumber%3DINC03459878%5EORDERBYnumber)
- prod: [INC03459886](https://emory.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D87e1cf701b5b54d0c725964c0a4bcb27%26sysparm_record_target%3Dincident%26sysparm_record_row%3D1%26sysparm_record_rows%3D1%26sysparm_record_list%3Dnumber%3DINC03459886%5EORDERBYnumber)

**Comment by SolomonHD** [comment]
I have created a wiki in the DLP space about creating a fedora user in [aws_at_emory](https://wiki.service.emory.edu/display/DLPP/Creating+Fedora+Commons+User+in+aws@emory)

**Comment by lovinscari** [comment]
Paul Peterson contacted SH asking for more details as to why profiles would not work. SH will respond to Paul.

**Comment by SolomonHD** [comment]
I sent Paul and email with DG CC'd asking for an ETA on the fedora user requests.

**Comment by SolomonHD** [comment]
We have a meeting tomorrow at 8:30 with Paul Petersen and security to discuss this issue

**Comment by lovinscari** [comment]
Security team is escalating this to their leadership

**Comment by SolomonHD** [comment]
We had another meeting. Our users have been approved contingent on signatures needed on a risk assessment document and we can't store the creds in github. They will enable AWS Secrets Manager, we're supposed to use that instead.

**Comment by libdgg** [comment]
Security Assessment Document Reviewed, signed and returned 10/13/2020. Risk Descriptions and Remediation Approaches are as follows:
1. User can share secrets with unauthorized, external, or non-Emory AWS accounts. Remediation: Warn Middleware and Developer teams of this risk.
2. User could configure or code secret rotation in a way where secret could be exposed in clear text logs. Remediation: Train Middleware and Developer teams on proper AWS Secret Manager usage.
3. User could misconfigure permissions and lock themselves out of their secret. Remediation: Train Middleware and Developer teams on secret manager rotation to avoid this risk.

**Comment by SolomonHD** [comment]
Paul Petersen dropped the user account credentials into the aws-account-247-ct1/svc bucket last night around 9PM. I've already copied them to the appropriate place. They will be removed via lifecycle policy today at ~9PM.

The policies attached to the users looks good.
