### ISSUE TITLE
Setup Avalon Prod Instance and Conduct Terraform Apply in Unrestricted AWS Environment

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#3]
After completing knowledge transfer with Solomon please complete the following for Unrestricted  AWS Environments for Avalon Prod

**Thursday 9/3**
- [x] Get Avalon running in unrestricted AWS account (running in a different region)
- [x] Confirm that CB, DM, WU, BW, AZ, DG, AN, AC has access to AWS for Terraform Apply or other work
- [x] Complete this ticket

**Friday 9/4**
- [ ] Update technical documentation in the wiki

**Comment by libdgg** [comment]
Solomon is researching and how backend is setup and where state files are going to be.

**Comment by libdgg** [comment]
Solomon is doing a write-up in ticket 81 that will help Mark proceed with this ticket.

**Comment by libdgg** [comment]
In progress. Begin setting up the environment on local machine.

**Comment by lovinscari** [comment]
Mark sidetracked on Friday, 9/11 but will be working on this today, 9/14/20.

**Comment by mprefer** [comment]
Created "prod.tfvars" file and added it to the GitHub repo.
Tested with "terraform plan -var-file=prod.tfvars"
Ran successful "terraform apply -var-file=prod.tfvars"
Ran successfule "terraform destroy -var-file=prod.tfvars"
Ran another "apply" to have an environment to work with.
