### ISSUE TITLE
Confirm access to Unrestricted AWS Environments for Test, Arch, and Prod

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#30]
- [x] Will
- [x] Doug
- [x] Ann
- [x] Collin 
- [x] Devanshu
- [x] Brad
- [x] Alex
- [x] Zo
- [x] Solomon
- [x] Mark

**Comment by lovinscari** [comment]
Question from Alex - " I may have gotten my AWS meetings confused :disappointed: ... if this is for middleware to walk Ann and me through setting up access to AWS, I don't see a meeting. But I don't think it's as urgent as needs to be done this sprint. "

**Comment by libdgg** [comment]
Per Solomon's slack message: I have created AWS accounts in the LTDS Standard account for: wulman dgoans libah cbrittl dmatlaw bwatso9 acoope5 azotov   I sent them their initial passwords via Slack DM.

**Comment by libdgg** [comment]
Alex confirmed in slack he was able to log into AWS as was set up by Solomon.
