### ISSUE TITLE
Document setup of restricted AWS Test Environment, Application of  Terraform,  and conduct knowledge sharing as part of process

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#32]
- [x] LTDS Wiki space created for Avalon to deposit documentation https://wiki.service.emory.edu/pages/viewpage.action?pageId=172512552
- [x] Added first version of a "[getting started](https://wiki.service.emory.edu/display/ULTS/Avalon+Terraform+Apply+-+Getting+Started
)" documentation, including links to tools as well (i.e. install TKI client, AWS CLI client, other info)
- [x] Check on existing documentation (noted in the wiki page draft) and either link to copy info over to complete this first version of a "getting started" document for Terraform Apply.
- [x] Add documentation from what we learned from Phuong. Especially any edits or changes needed locally for Emory and our project
- [ ] Acceptance testing of the documentation (ensuring it is viable for any future use or reference)

**Comment by lovinscari** [comment]
Wiki space is setup but nothing has been added by Middleware Team at this point. Plan is for DG to get with AH, SH, MP to look at the documentation that can be completed by the end of the week.

**Comment by libdgg** [comment]
SH, MP, AH, AC and DG met to implement a first version of documentation in our wiki. Barring any questions or concerns from the team, we can close this ticket and review documentation for updates as we complete the work in the AWS@emory environment for production.

**Comment by lovinscari** [comment]
DG to complete the initial review and will then send to everyone for review.

**Comment by lovinscari** [comment]
Doug to review the documentation.

**Comment by libdgg** [comment]
Moving to blocked as the ART review work, requesting Phuong's assistance and other Avalon project work is taking precedence this week.

**Comment by libdgg** [comment]
@libah Would you be able to schedule some time to do a review of the documentation we have for the unrestricted environment work for acceptance? Please make any notes of your findings and if we can accept/close with any conditions or recommendations. Please let me know if you have questions, preference or suggestions. Thanks.

**Comment by libdgg** [comment]
@libah FYI this issue is being re-factored for the restricted environment. We'll move this back into queued for now.

**Comment by SolomonHD** [comment]
Updates:
I've added new sections to the [wiki](https://wiki.emory.edu/pages/viewpage.action?pageId=172512552). Detailing backup strategy, general information about avalon, and specifics about how authentication works. 

Avalon already has a "getting started from zero" section in the avalon-terraform repo [README](https://github.com/emory-libraries/avalon-terraform). I do plan on adding a section to the wiki about deploying.

**Comment by SolomonHD** [comment]
Moving this into accept, I've written multiple wiki articles about the process.

[Link](https://wiki.emory.edu/display/ULTS/Avalon+Terraform+Apply+and+Deploys)
[Link](https://wiki.emory.edu/display/ULTS/Avalon+General+Infomation)
[Link](https://wiki.emory.edu/pages/viewpage.action?pageId=185338624)

And I've updated the [README](https://github.com/emory-libraries/avalon-terraform/blob/main-emory/README.md) on the avalon-terraform repo to reflect our differences with the main avalon-terraform

**Comment by libdgg** [comment]
@devanshu-m and @libah please review the wiki documents above

**Comment by libah** [comment]
I reviewed the wiki documents and think they are both clear and complete.
