### ISSUE TITLE
Testing and confirmation of Terraform apply to the restricted environments

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#37]
This is done when we can view added content in Avalon

**Comment by lovinscari** [comment]
Assigning to @AGCooper for testing after shib is configured and working correctly.

**Comment by AGCooper** [comment]
I should not be the one to test this.

**Comment by libdgg** [comment]
NOTE: per the standup 11/19/2020 if we can add a video to the prod system we can close this ticket.
