### ISSUE TITLE
Domain setup - open up to world

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#38]
https://avreserves.libraries.emory.edu
https://streaming.avreserves.libraries.emory.edu (we don't know yet if this needs it's own DNS or is just internal - terraform automatically creates this)

This work will setup F5 Tunnel between F5 and AWS@Emory Account
See servicenow task RFTASK87925 (this is what we asked for per Paul P. for the DLP).
This relies on things being semi-built out. Decide how many load balancers we want.

QUESTION
https://test.avreserves.libraries.emory.edu
https://arch.avreserves.libraries.emory.edu

ServiceNow Ticket (refer to DLP ticket from Solomon as a model): 
Request a tunnel from F5 opening up to the AWS@emory account and include the A record name avr.aws.emory.edu

Estimates a week to complete this with the DNS team. Might need a few calls if they have questions.

**Comment by libdgg** [comment]
https://avreserves.libraries.emory.edu

**Comment by SolomonHD** [comment]
The connection between F5 and ALB for prod has been established.

**Comment by libdgg** [comment]
SH put in SvcNow tickets for VIP and CNAME and add the ticket numbers here.

**Comment by libdgg** [comment]
NOTE: Shibboleth environment variables are in place. Wherever the routes are in the rails app there needs to be a route there for the oauth saml. What SH typically does with shibboleth is making one entry (instead of giving Gerry multiples). Ask for one and then add others as endpoints. All instances are prod for the entity ID. Gerry is good at adding enpoints. Adding the one for prod and then add the other 2 instances as endpoints (just give Gerry the urls).

**Comment by SolomonHD** [comment]
Ticket for new VIP [here](https://emory.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D7cf366441b4464104fd50e1dcd4bcbb3%26sysparm_record_target%3Dtask%26sysparm_record_row%3D1%26sysparm_record_rows%3D126%26sysparm_record_list%3Dopened_by%3Djavascript:gs.getUserID()%5Esys_class_name!%3Dsc_request%5Esys_class_name!%3Dsc_req_item%5EORDERBYDESCsys_created_on)

**Comment by libdgg** [comment]
VIP ticket was assigned this morning [INC03479806](https://emory.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D7cf366441b4464104fd50e1dcd4bcbb3%26sysparm_record_target%3Dtask%26sysparm_record_row%3D1%26sysparm_record_rows%3D126%26sysparm_record_list%3Dopened_by%3Djavascript:gs.getUserID()%5Esys_class_name!%3Dsc_request%5Esys_class_name!%3Dsc_req_item%5EORDERBYDESCsys_created_on)

**Comment by libdgg** [comment]
VIP ticket has been fulfilled [INC03479806](https://emory.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D7cf366441b4464104fd50e1dcd4bcbb3%26sysparm_record_target%3Dtask%26sysparm_record_row%3D1%26sysparm_record_rows%3D126%26sysparm_record_list%3Dopened_by%3Djavascript:gs.getUserID()%5Esys_class_name!%3Dsc_request%5Esys_class_name!%3Dsc_req_item%5EORDERBYDESCsys_created_on)https://avreserves.libraries.emory.edu/ is up on the F5

**Comment by libdgg** [comment]
@lovinscari Please visit the url to confirm if you have any questions or concerns. If not please accept the ticket and we can move it to closed.

**Comment by lovinscari** [comment]
SH submitting SN ticket to open domain.

**Comment by rotated8** [comment]
According to Elliot, we have a temporary firewall exception that will end on the 24th. This ticket is now blocked by #106 (which will make the firewall exception permanent), and won't be available for testing until after that date.

**Comment by libdgg** [comment]
NOTE: Elliot extended our firewall exception to Dec 4th

**Comment by rotated8** [comment]
Via an email with Elliot, our exception is now permanent.
