### ISSUE TITLE
Acceptance Testing: Canvas LTI Integration

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#54]
First pass to test (we will accept again after we resolve the x-frame issue).

STEP 1: Test now before headers change
- [x] Add video to prod
- [x] Test
- [x] Merge headers ticket

STEP 2: Test after headers change
- [x] Test prod again
- [x] close headers ticket
- [x] Collin inform security
- [x] Soft. Eng. team then test prod again
- [x] Officially close ticket #106 and proceed with Step 3 below.

STEP 3: Final test to confirm that James Steffen and Nina Rao can
- [x] Login to Avalon with Manage permissions
- [x] Confirm ability to create collection and upload video and manage any metadata needed
- [x] Confirm the uploaded video is accessible from Canvas
- [x] Confirm the ability to remove/expire video objects and collections and that the change is reflected in Canvas
- [x] Confirm users are not able to download videos

**Comment by libdgg** [comment]
Per the check-in with Devanshu, Brad and Solomon on 12/4 at 10:30am.
We updated the checkbox list at the top of the ticket. Collin will inform security as the next step.

**Comment by lovinscari** [comment]
@libdgg and @lovinscari to complete step 3 of ticket.

**Comment by libdgg** [comment]
I updated step 3 of this ticket for our meeting with James

**Comment by libdgg** [comment]
Update acceptance requirements checklists for this ticket and updated the estimate.

**Comment by rotated8** [comment]
Check-offs are complete, closing
