### ISSUE TITLE
Determine, Confirm and Implement backup/restore

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#57]

**Comment by libdgg** [comment]
Files in S3 are coped into 2 buckets. Database snapshots are turned on via terraform scripts. 
We need to determine what recovery looks like.
Until we get content into the application we don't have a need to test backup and explore.
ACTION: add dependency to this ticket about content being in the system first.

**Comment by lovinscari** [comment]
SH reviewed the scripts and did confirm snapshots are made everyday. He will check on the other part.

**Comment by libah** [comment]
Need to be able to add content before testing

**Comment by libah** [comment]
I added the dependency about adding content before we can determine if files in S3 are copied into 2 buckets.

**Comment by libah** [comment]
Maybe this should be moved to queued since I can’t actually test until there’s content. There are buckets, but that’s all I can determine without content.

**Comment by SolomonHD** [comment]
I've done a write up on all I understand and know about Avalon's backup and restore process:

[Wiki Link](https://wiki.emory.edu/display/ULTS/Avalon+Backup+Strategy)

**Comment by libdgg** [comment]
NOTE: ticket #59 is related and we could close this ticket as documentation and use ticket #59 as the actual acceptance test for running a restoration.
