### ISSUE TITLE
Estimate any AWS and storage costs

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#6]
AWS calculator https://aws.amazon.com/elastictranscoder/pricing/

**Comment by lovinscari** [comment]
DG would like to get a better handle on the costs using the estimator from Northwestern. This will be furthering the conversation with James to determine the number of DVD's planned for upload. 

Risk if not completed by 9/11/20 - Unknowns with cost.

**Comment by libdgg** [comment]
Plan: See about abstracting costs for AWS based on Solomon's work so far. See if James has any known DVD/media that will be used and we could provide costs from that, otherwise unknown costs for content/media is acceptable at this phase of the project.

**Comment by libdgg** [comment]
We think we can unblock this in about a week or so. We would be able to determine minimum costs for operating the site.

**Comment by libdgg** [comment]
We now have environments in restricted so we can plan this work.

**Comment by libdgg** [comment]
Have not done anything on this ticket yet, finishing up other tickets instead.

**Comment by libdgg** [comment]
AWS cost and billing info for account 247 (Avalon) is as follows (rounding figures):

July 2020: $71
Aug 2020: $96
Sep 2020: $75
Oct 2020: $205
Nov 2020: $320
Dec 2020: $325

TOTAL: $1092 for the past 6 months

Plan is to start monitoring costs going forward as part of operations.
