### ISSUE TITLE
Acceptance Test: Branding/UI

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#69]
Ensure and acknowledge that the following roles have reviewed the branding and UI of the product (stand-alone and via Canvas) and agree it is ready for operational use by student s and instructors.
- [x] Web Product Manager (Rosalyn) - approved - need to update the logo at the bottom - will create a new ticket for that
- [x] Technology Lead [Collin]
- [x] Service Manager (James)

**Comment by rotated8** [comment]
Blocked waiting for UI tickets/epic to close.
