### ISSUE TITLE
Confirm access to Restricted AWS Environments

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#76]
**Tuesday, 9/8
SCOPE: sign into the AWS console for account 247

- [x] Will
- [x] Doug
- [x] Ann
- [x] Collin 
- [x] Devanshu
- [x] Brad
- [x] Alex
- [x] Zo
- [x] Solomon
- [x] Mark

**Comment by lovinscari** [comment]
This is looking at either accessing to the AWS@Emory console or SSH'ing into servers.

**Comment by libah** [comment]
Can't ssh. Need access to the core, can access the console.

**Comment by bwatson78** [comment]
@SolomonHD I have edited my hosts:

![Screen Shot 2020-10-15 at 10.55.44 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/b0c59596-ba1b-4905-898b-e9df18dfe6fd)

and have attempted to ssh into both environments:

![Screen Shot 2020-10-15 at 10.57.13 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/156b5a4f-4683-41ed-85ff-2aa42577e297)

No luck. Going to restart VPN.

**Comment by libdgg** [comment]
I am able to access the aws-account-247 console and I can see EC2 Instances for ltds-arch-compose and ltds-test-compose.
