### ISSUE TITLE
Domain Setup CNAME for internal VPN beta

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#80]
Service Catalog DNS form to setup https://avreserves.libraries.emory.edu for internal VPN beta in October.
We need to get the ALB name first which means ticket #78 needs to be first before we can complete this.

**Comment by SolomonHD** [comment]
arch and test have working cnames to their ALBs. Prod is still a work in progress.

**Comment by libdgg** [comment]
Prod instance - ALB prod to F5 is open. After the VIP and CNAME are in place for prod we should be able to see it when we are on VPN.
