### ISSUE TITLE
Ability to get all 3 environments applied at one time

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#81]

**Comment by libdgg** [comment]
We discovered this past week that standing up either an arch or prod instance destroyed the test instance that was setup first. Solomon is investigating solutions to standup multiple environments without destroying existing ones.

**Comment by lovinscari** [comment]
This work has not been completed. Need to rework how backend of Terraform works. Hoping to get to this today (SH) - just need to change a few lines of code.

**Comment by SolomonHD** [comment]
I do have this solved but this was more complicated than I thought. Terraform has a concept of workspaces, which are essentially separate state files which is what we needed. I have redone the backend to utilize workspaces. Backend changes seem to cause issues for others running terraform, please follow these steps exactly before attempting to run terraform again.

1. Delete whatever existing copy of avalon-terraform that you have
2. git clone git@github.com:emory-libraries/avalon.git
3. git-crypt unlock
4. git checkout test-generic-ami
5. terraform init

You should now be caught up on all changes
If you run `terraform workspace list` There should be 4 workspaces default, arch, test and prod, switch terraform workspaces with this command: `terraform workspace select [env]` Then run `terraform apply -var-file="[env].tfvars"` or to destroy `terraform destroy -var-file="[env].tfvars"`

**Comment by SolomonHD** [comment]
Even with all of these changes I am running an issue when trying to create test (while arch also exists)
`Error: error creating ECR repository: RepositoryAlreadyExistsException: The repository with name 'avalon' already exists in the registry with id '[aws account name]`

There seems to be something hard coded to "avalon" when most likely it's supposed to be "avalon-[env]" I'll create a ticket in the OG avalon-terraform repo

**Comment by SolomonHD** [comment]
I've added updated instructions on how to apply with the new repo setup. It's in the wiki here:

https://wiki.service.emory.edu/pages/viewpage.action?pageId=172512552
