### ISSUE TITLE
Determine how Terraform names buckets

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#82]

**Comment by rotated8** [comment]
@SolomonHD I found five buckets- one in `terraform.tfvars.example`:
- `mystack-state`
and four in `s3.tf`:
- `${local.namespace}-masterfiles`
- `${local.namespace}-derivatives`
- `${local.namespace}-preservation`
- `${local.namespace}-fedora-binaries`
where `${local.namespace}` (defined in `variables.tf`) is `${var.stack_name}-${var.environment}`. Also defined in `variables.tf`, `${var.stack_name}` defaults to "stack", and ${var.environment} (which lives in `terraform.tfvars.example`) defaults to "dev". So, by default, the full name of those buckets is:
- `stack-dev-masterfiles`
- `stack-dev-derivatives`
- `stack-dev-preservation`
- `stack-dev-fedora-binaries`

**Comment by lovinscari** [comment]
Solomon to talk to Phuong about this and then finalize the items on this ticket.

**Comment by SolomonHD** [comment]
So I've decided to name our stack "ltds" so the buckets created will be:

- ltds-arch-fedora-binaries
- ltds-prod-fedora-binaries
- ltds-test-fedora-binaries

I will submit tickets for users with access to these buckets
