### ISSUE TITLE
Partner with Phuong on identifying issues specific to Emory AWS Environments, Terraform, and problems with streaming

### ISSUE THREAD

**Issue by lovinscari** [emory-libraries/avalon#85]
Work with Rosalyn to determine if Emory LTDS team can contract with Phoung from Indiana University on some of the issues currently experienced with Terraform and AWS@Emory, and issues with not being able to stream content. 

- [x] Solomon to update Ticket #78 with specific details that need to be addressed for AWS@Emory

Dependency prior to commencing work with Phuong -

- [x] Completed request proposal for Indiana Universities with specific issues that will be addressed if the request is approved (Goal, Objectives, Change Details, Script Changes Identified)
- [x] Adding Indiana in our payment system (to be able to pay them)
- [x] Approval of the request by Emory and Indiana
- [x] Sponsored account setup for Phuong
- [x] Ensure sponsored account that mirrors accounts for Middleware Team - access to restricted AWS environment
- [x] VPN access for Phuong
- [x] Elevated VPN access (access to AWS at Emory - REQ102693 submitted and completed 10/5/2020)
- [x] Need any remaining AWS Restricted accounts setup for the team
- [x] ZenHub/GitHub access for Phuong?
- [x] Add Phuong to LTDS avalon slack (invitation sent)
- [x] Confirm Phuong's calendar/availability/preferences (for agreement work and also in context of Blacklight and Samvera, etc)
- [x] Draft agenda for kick-off meeting
- [x] For kick-off: Solomon, Mark, Ann, Collin, Doug, Phuong, Haynes (Optional: Alex, Cari) - 90 minutes - Identify what is the work that needs to be done and how will the work be done. Phuong will be consulting. Will there be working sessions and who will be attending them?

**Comment by lovinscari** [comment]
@libdgg - can you please review this issue to see if I missed anything?

**Comment by libdgg** [comment]
Request submitted to Jon at Indiana. Jon responded and they are reviewing the request on their end. They will need to draft an agreement that we will need to review. Moving to blocked until we get the next response and/or next steps.

**Comment by libdgg** [comment]
Request for sponsored account submitted 9/22/2020 - REQ102303

**Comment by libdgg** [comment]
Emailed Jon at Indiana to check on the status of the agreement and asked for a response by 5pm Tuesday October 6th.

**Comment by libdgg** [comment]
We have completed the requests for access permissions.
