### ISSUE TITLE
Request Security Scan

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#87]

**Comment by libdgg** [comment]
The team thinks this may have already been done (also because of the security concern with the x-frame headers). We can plan on confirming if this has already been done.

**Comment by libdgg** [comment]
I contacted Elliot today (12/8/2020) to confirm and inquire about completion status or next steps.

**Comment by libdgg** [comment]
@libdgg have Elliot run it in test first.

**Comment by libdgg** [comment]
@solomon and @rotated8 Since Elliot ran the scan in our avalon test instance, can you all tell if anything went wrong with performance or did the test add any garbage to the back-end or other issues?

**Comment by Solomon** [comment]
Wrong Solomon!

**Comment by libdgg** [comment]
@SolomonHD will check for any garbage or issues in the back-end
@devanshu-m will review the report for any next steps related to headers

**Comment by devanshu-m** [comment]
I will create a new ticket for header recommendations and put it in new issues.

**Comment by libdgg** [comment]
@SolomonHD please confirm if any garbage or issues were added to the back-end of the test instance of avalon (or if they were not) by adding a comment on this ticket in zenhub. Thanks -DG

**Comment by libdgg** [comment]
DG will ask Elliot to run scan on prod.

**Comment by libdgg** [comment]
Elliot ran the scan on 1/19/2021 and reports that the only issues it found were related to missing optional security-related HTTP headers and loose cookie security settings.

copies of the scan results are here: https://emory.app.box.com/folder/130051272570

**Comment by libdgg** [comment]
@rotated @SolomonHD @mprefer please see the scan results linked above and let me know if this is ok to close (acceptable risks) or if there are things we need to address at this time.

**Comment by rotated8** [comment]
I am happy to accept the risks as is. +1 for closing.

**Comment by libdgg** [comment]
Solomon responded in slack "It looks like the remaining issues are low in risk, If Elliot is not complaining about them then I think they're fine."

**Comment by libdgg** [comment]
Mark will review today and let DG know if risks are acceptable.

**Comment by libdgg** [comment]
Mark responded in slack "I looked and everything is either informational or low. I don't think the lows are significant, unless Eliot thinks otherwise. I'll look at it and see what headers we can add, but since they are low, not going to dash."

**Comment by libdgg** [comment]
Closing this ticket as the risks are low and Elliot and the team are not identifying any immediate actions to take.
