### ISSUE TITLE
Create student account for testing

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/avalon#90]
Create an account with student-like access. It should not be able to access all the content in Avalon, but be able to access something.

**Comment by alexBLR** [comment]
- Login with DB or OAuth or Shib
- Identify if it is possible
- Canvas user come from (Oath)
- Take at Avalon docs

**Comment by alexBLR** [comment]
Avalon allows implementation with Canvas which is specified in the docs here:
https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+LTI+Tool

Canvas allows for the specification of global as well as course-specific LTI providers. From either the Global or the Course Settings, click Apps, then View App Center to reveal the Add New App button.

![Screen Shot 2020-10-16 at 9.52.37 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/d0f6ebc9-7cd4-4e16-8a2f-b5bf3dc377b5)


![Screen Shot 2020-10-16 at 9.52.26 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/738c2475-09d1-4dcc-a970-4d4bff0cc8ce)
