### ISSUE TITLE
Change the main colors on the site

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/avalon#91]
Rather than green and yellow, the site should use blue and gold, from Emory's branding.

Colors can be obtained from the branding website: https://brand.emory.edu/color.html

**Comment by wulman16** [comment]
![Screen Shot 2020-10-08 at 10.38.57 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/506ce30a-5afb-42a4-b0de-a21bf800d2f1)
GitHub branch with Emory colors: https://github.com/emory-libraries/avalon/tree/colors
Backgrounds, links, and buttons (including hover states) are changed to use Emory brand colors

**Comment by lovinscari** [comment]
This was deployed to the unrestricted environment

**Comment by lovinscari** [comment]
Moving forward - everyone should be able to deploy CodeBuild themselves either from the command or GUI button. Solomon will post the command for this. Further instructions should be available once Solomon reviews CodeBuild instructions with Phuong.

**Comment by lovinscari** [comment]
Need to deploy to Arch and Prod unrestricted environments.

**Comment by lovinscari** [comment]
CL to review and ping RM to see if she has any input.

**Comment by rosy1280** [comment]
Took a look at Prod and all looks well.
