### ISSUE TITLE
Start using Emory's Avalon in deployments.

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/avalon#92]
Rather than using the upstream Avalon repo, use ours.

**Comment by lovinscari** [comment]
This needs to be pushed out to Arch and Prod. Solomon has already taken care of Test. Need to hold off until after Solomon has worked with Phuong on knowledge transfer around CodeBuild.

**Comment by lovinscari** [comment]
Need to make a few adjustments to CodeBuild for each environment.

**Comment by lovinscari** [comment]
Terraform template has been updated to point to Emory by default.
