### ISSUE TITLE
Replace default Avalon logo with Lux logo

### ISSUE THREAD

**Issue by wulman16** [emory-libraries/avalon#95]
![Screen Shot 2020-10-09 at 3.22.01 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/fbcd89db-f169-49ff-a2d5-b82d01d492f9)

![Screen Shot 2020-10-09 at 3.20.36 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/9619a5fc-9258-4b41-a3a5-ab16bdbae306)

https://github.com/emory-libraries/dlp-lux/blob/main/app/views/shared/_big_nav.html.erb

**Comment by rosy1280** [comment]
@wulman16 if you can do that swap, that would be great.

**Comment by wulman16** [comment]
@rosy1280 This work has been merged onto the master branch. It's ready to be deployed.

**Comment by libdgg** [comment]
Move to "deploy"  since it hasn't been deployed yet.

**Comment by lovinscari** [comment]
Solomon is going to do a rebuild of the CodeBuild so this is on hold until the deploy process is updated.

**Comment by lovinscari** [comment]
@rosy1280 - Can you please take a look at this once more and approve?

**Comment by rosy1280** [comment]
everything looks good.  thanks @wulman16
