### ISSUE TITLE
Security Risk Remediation

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#96]
Ensure that the middleware and developer teams understand this risks and remediations as follows and any next steps or actions to support remediation:
1. User can share secrets with unauthorized, external, or non-Emory AWS accounts. Remediation: Warn Middleware and Developer teams of this risk.
2. User could configure or code secret rotation in a way where secret could be exposed in clear text logs. Remediation: Train Middleware and Developer teams on proper AWS Secret Manager usage.
3. User could misconfigure permissions and lock themselves out of their secret. Remediation: Train Middleware and Developer teams on secret manager rotation to avoid this risk. 

Acknowledgement of [this document](https://emory.app.box.com/file/766672962885)

- [x] Solomon Hilliard
- [x] Alex Cooper
- [x] Collin Brittle
- [x] Mark Prefer
- [x] Ann Hulton
- [x] Alex Zotov
- [x] Brad Watson
- [x] Devanshu Matlawala
- [x] Doug Goans

**Comment by libdgg** [comment]
ACTIONS:

1. For #1 plan to add this information in the training actions mentioned in #2 and #3.
2. DG will schedule meeting with CB, DG, SH about #2 and #3 to determine if security has training for proper AWS Secret Manager and/or other actions needed. 
3. We think a half hour presentation for the teams could address the above.

**Comment by libdgg** [comment]
Tentative meeting scheduled 11/5 to review risk items provided  by security and plan next steps for the LTDS team. -DG

**Comment by libdgg** [comment]
From Paul P. 11/05/2020 "We are working to enable Secrets Manager for the Library account.  The changes to make that happen are in our Staging environment.  Once we have verified everything is working in that environment, we will schedule a change to update the production environment.  I am aiming for next week, but it could be the week after."

**Comment by rotated8** [comment]
@Brad has written up some secrets best practices for Rails (and specifically AWS Secrets Manager) for Software Engineering, which is now [in Box](https://emory.app.box.com/file/740464507602)

**Comment by libdgg** [comment]
Waiting on confirmation that Secrets Manager is in place to then get team agreement in place for remediation which is acknowledging awareness of the issues and following practices.

**Comment by libdgg** [comment]
I have not heard if  the Secrets Manager is in place yet. I plan to reach out on the status by  tomorrow if I haven't heard anything before then.

**Comment by libdgg** [comment]
Still waiting on Paul Petersen to confirm. His email indicated that it could be this week so I plan to reach out Friday 11/20/2020 if I haven't heard anything more by then.

**Comment by libdgg** [comment]
Paul has not responded back if the Secrets Manager is in place. Doug will check with Rosalyn about a possible escalation plan. If Secrets Manager is not in place we do not expect that will block our delivery of the product. IT Security prompted us to mitigate the risks and we agreed. It is no on IT Security to put the Secrets Manager in place and we are waiting to hear back from them.

**Comment by libdgg** [comment]
Per Paul's email on 12/8/2020
"A few weeks ago, when we pushed the new policy to allow Secrets Manager in the Library AWS account (aws-account-70) to our Staging environment, we discovered an unrelated bug with our Security Risk Detection service.  This issue has been resolved and the new policy with Secrets Manager for the Library has passed testing in the Staging environment, and the policy is scheduled to be pushed to production tomorrow (12/9) between 5-7pm.  After this change, Secrets Manager should work in the Library account."

**Comment by libdgg** [comment]
I'm keeping this ticket in blocked until we have confirmation that it is in production.

**Comment by libdgg** [comment]
Paul has confirmed the following "You should be able to use Secrets Manager in aws-account-70."

**Comment by libdgg** [comment]
UPDATE:  Account 70 is the DLP account, account 247 is the avalon account. Solomon tested them both. Secrets Manager works in account 247, not 70. It's what we asked for.

**Comment by libdgg** [comment]
Next step is getting the team agreement in place for remediation which is acknowledging awareness of the issues and following practices. Doug will draft the agreement.

**Comment by libdgg** [comment]
Steps are to finish the acknowledgement work.
Plan on implementing Secrets Manager after the break (it is not a dependency to move us into operations).

**Comment by libdgg** [comment]
Wrote up the security risk mitigation acknowledgement document for AWS secrets for the scrum team to agree to via a box task.
https://emory.app.box.com/file/766672962885

**Comment by libdgg** [comment]
@mprefer @libah @devanshu-m @alexBLR @bwatson78 please review the document (linked in box above) and let me know your acknowledgement to agree. the box approval may not be working so let me know if you agree here or send me an email. please let me know if you can not access the document or if you have questions about it.
