### ISSUE TITLE
Use LDAP groups to assign admin roles to shib users

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/avalon#99]
NEW WAY: input a comma separated list of LDAP groups that will be allowed to login via shib.

OLD WAY:

We need to implement a way to create users in avalon since we have shib configured and need to create the required user objects in the database. Thinking of something similar to what we did in curate using a yml file. More detail later.

Refer: https://github.com/emory-libraries/dlp-curate/blob/main/lib/user_setup.rb

**Comment by libdgg** [comment]
The users in this case are for system admins (not for students). Solomon and Devanshu will look at this.

**Comment by devanshu-m** [comment]
First step, i.e., to refine omniauth response hash and extract groups from the response is done. Starting tomorrow will work to use those extracted groups to do matching with comma separated input from env variable.

I will first push up all the work that we did to get login working.

**Comment by devanshu-m** [comment]
PR: https://github.com/emory-libraries/avalon/pull/113

Everyone in DLP_DEVELOPERS and AvalonApp admin list should be able to login to avalon via shibboleth.

**Comment by devanshu-m** [comment]
Testing login:

Should be able to login (at least on one admin group):
- [ ] Alex Cooper
- [ ] Ann
- [ ] Alex Zotov
- [ ] Mark P

Should not be able to login (since they are not on any admin group):
- [ ] Will Ulman
- [ ] Brad Watson

**Comment by bwatson78** [comment]
@devanshu-m I received `Unable to authorize because "you aren't authorized to use this application."` on both SAML options. 
It also appears I'm the last to test this.

**Comment by devanshu-m** [comment]
@bwatson78 @wulman16 you guys should now be able to login. Last step before pushing this to prod.

- [ ] Will
- [ ] Brad

**Comment by devanshu-m** [comment]
Users logging in via shib should now be admins.

**Comment by devanshu-m** [comment]
Can a couple people please test if they have admin access so this can move to `to deploy prod`

@libah @bwatson78 @wulman16 

- [ ] Ann
- [ ] Brad
- [ ] Will

**Comment by libah** [comment]
I can login as admin create a collection then, upload media. I get a network error when trying to view any of the uploaded media though.

**Comment by SolomonHD** [comment]
@libah That error should now be fixed

**Comment by devanshu-m** [comment]
I am able to login as admin via shib on prod. Ok to close this?

**Comment by AGCooper** [comment]
@devanshu-m I can login but can't see the Manage button/tab. I am in the Avalon App group (at least last time I checked).

**Comment by devanshu-m** [comment]
@AGCooper which env are you testing this on? This code is on test and prod. Can you please send a screenshot of your homepage? Thanks.

**Comment by AGCooper** [comment]
@devanshu-m Test I believe:

![image.png](https://images.zenhubusercontent.com/5c75948e37910a45fad7cb77/5441e06d-42aa-43dd-9c21-87386569cacb)

**Comment by bwatson78** [comment]
@devanshu-m I have the manage option and can access all of the Manage pages except "Manage Users". I get an error message when trying to access that

**Comment by AGCooper** [comment]
Okay I get the tab now. Thanks @devanshu-m
